# Assignment-3

# Questions 1:

# Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr=np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:

# Accept two lists of 5 elements each from the user.

# Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [2]:
list1=[]
for i in range(5):
    x=int(input())
    list1.append(x)
print(list1)
print()

list2=[]
for i in range(5):
    y=int(input())
    list2.append(y)
print(list2)
print()

arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = np.concatenate( (arr1,arr2) )
print(arr3)
print(np.sort(arr3))

11
12
13
14
15
[11, 12, 13, 14, 15]

16
17
18
19
20
[16, 17, 18, 19, 20]

[11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20]


# Questions 3:

# Write a code snippet to find the dimensions of a ndarray and its size.

In [5]:
a = np.array([[11,12,13],[13,14,15],[15,16,17],[17,18,19],[19,20,21]])
print("Number of dimensions",a.ndim)
print("The shape of the dimension",a.shape)
print("Size of array",a.size)

Number of dimensions 2
The shape of the dimension (5, 3)
Size of array 15


# Questions 4:

# How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

# Hint: np.newaxis, np.expand_dims

In [7]:
a_1d = np.array([18,19,15,16,14,13,12,11,17])
a_2d = a_1d[np.newaxis]
a2 = np.expand_dims(a_1d, axis=(1,-2,3))
a2.shape

print(a_1d)
print(a_1d.shape)
print()
print(a_2d)
print(a_2d.shape)

[18 19 15 16 14 13 12 11 17]
(9,)

[[18 19 15 16 14 13 12 11 17]]
(1, 9)


# Questions 5:

# Consider two square numpy arrays. Stack them vertically and horizontally.

# Hint: Use vstack(), hstack()

In [8]:
v = np.array([[8,7],[4,3],[9,7]])
h = np.array([[2,5],[3,7],[8,6]])

print("Vertical Stack")
print(np.vstack((v,h)))
print()
print("Horizontal Stack")
print(np.hstack((v,h)))

Vertical Stack
[[8 7]
 [4 3]
 [9 7]
 [2 5]
 [3 7]
 [8 6]]

Horizontal Stack
[[8 7 2 5]
 [4 3 3 7]
 [9 7 8 6]]


# Questions 6:

# How to get unique items and counts of unique items.

In [11]:
x = np.array([1,2,3,5,4,2,72,3,5,6,8,54,6,7,9,62,44,96,6,37,55,33,88,44,37,1,4])
unique, count = np.unique(x, return_counts = True)
print("Unique Items:",unique)
print("Unique Items Count:",count)

Unique Items: [ 1  2  3  4  5  6  7  8  9 33 37 44 54 55 62 72 88 96]
Unique Items Count: [2 2 2 2 2 3 1 1 1 1 2 2 1 1 1 1 1 1]
